# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-03 16:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Refpoint',
            fields=[
                ('r_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('r_position', models.CharField(max_length=64)),
                ('r_addr1', models.CharField(max_length=64)),
                ('r_addr2', models.CharField(max_length=64)),
                ('r_addr3', models.CharField(max_length=64)),
                ('r_rssi1', models.CharField(max_length=64)),
                ('r_rssi2', models.CharField(max_length=64)),
                ('r_rssi3', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='User_position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_position', models.CharField(max_length=64)),
                ('u_datetime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Users_script',
            fields=[
                ('u_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('u_username', models.CharField(max_length=64)),
                ('u_fullname', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='user_position',
            name='u_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_name', to='show_position.Users_script'),
        ),
    ]
